// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp01.Data;

namespace MyWebApp01.Migrations
{
    [DbContext(typeof(MyWebApp01Context))]
    partial class MyWebApp01ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApp01.Models.Timesheet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("changedate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.Property<string>("empname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("task")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Timesheet");
                });
#pragma warning restore 612, 618
        }
    }
}
